services:
  conaprole.orders.api:
    image: conaprole.orders.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Conaprole.Orders.Api/Dockerfile
    depends_on:
      conaprole.orders-db:
        condition: service_healthy
      conaprole-idp:
        condition: service_healthy
    ports:
      - "8080:8080"
  conaprole.orders-db:
    image: postgres:latest
    container_name: Conaprome.Orders.Db
    environment: 
      - POSTGRES_DB=conaprole.orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  conaprole-idp:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: Conaprole.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s